import re

# Read the file
with open("C:\\Users\\Ahmed\\Desktop\\OpenToCode\\src\\ECommerce.Application\\Products\\Services\\ProductService.cs", "r") as f:
    content = f.read()

# Add image upload handling to CreateAsync
content = content.replace("await _productRepository.AddAsync(product, cancellationToken);", "await _productRepository.AddAsync(product, cancellationToken);\\n\\n        // Handle product image upload\\n        if (request.Image != null && request.Image.Length > 0)\\n        {\\n            var imageResult = await HandleProductImageUploadAsync(product.Id, request.Image, cancellationToken);\\n            if (!imageResult.IsSuccess)\\n            {\\n                return Result<ProductDto>.Failure(imageResult.ErrorCode, imageResult.ErrorMessage);\\n            }\\n        }")

# Add the HandleProductImageUploadAsync method
image_handler = "\\n\\n    private async Task<Result> HandleProductImageUploadAsync(Guid productId, IFormFile imageFile, CancellationToken cancellationToken)\\n    {\\n        // Validate file extension\\n        var allowedExtensions = new[] { \".jpg\", \".jpeg\", \".png\", \".gif\", \".webp\" };\\n        var extension = Path.GetExtension(imageFile.FileName).ToLowerInvariant();\\n        \\n        if (string.IsNullOrEmpty(extension) || !allowedExtensions.Contains(extension))\\n        {\\n            return Result.Failure(\"Invalid file extension. Allowed: .jpg, .jpeg, .png, .gif, .webp\", \"INVALID_IMAGE_EXTENSION\");\\n        }\\n\\n        // Validate file size (max 5MB)\\n        const long maxSize = 5 * 1024 * 1024; // 5MB\\n        if (imageFile.Length > maxSize)\\n        {\\n            return Result.Failure(\"Image size must be less than 5MB\", \"IMAGE_SIZE_TOO_LARGE\");\\n        }\\n\\n        // Create uploads directory if not exists\\n        var uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), \"wwwroot\", \"uploads\", \"products\");\\n        if (!Directory.Exists(uploadsPath))\\n        {\\n            Directory.CreateDirectory(uploadsPath);\\n        }\\n\\n        // Generate unique filename\\n        var fileName = $\"{Guid.NewGuid()}{extension}\";\\n        var filePath = Path.Combine(uploadsPath, fileName);\\n\\n        // Save file\\n        using (var stream = new FileStream(filePath, FileMode.Create))\\n        {\\n            await imageFile.CopyToAsync(stream, cancellationToken);\\n        }\\n\\n        // Create image URL\\n        var imageUrl = $\"/uploads/products/{fileName}\";\\n\\n        // Add image to product\\n        product.AddImage(imageUrl);\\n\\n        return Result.Success();\\n    }\\n"
